### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by Jan200101** [Jan200101/polecat#1]
things to do until 0.2.0
- [x] install wine versions into a data directory (0.1.1)
- [x] run wine directly from polecat (0.1.2)
- [x] untar in memory (0.1.4)
- [x] parsing lutris scripts (0.1.4)
- [x] create variable parser (can variables be unicode?)
- [ ] installing lutris scripts
- [ ] store downloaded content in a temporary cache directory
- [ ] manage the cache directory (cleanup, etc.)
- [ ] json configs
- [x] add ability to install DXVK to specific wine installation

**Comment by Jan200101** [comment]
replaced with the roadmap in the projects sections
